version: "3.9"
services:
  bot:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: spamdb
      POSTGRES_USER: spamuser
      POSTGRES_PASSWORD: spampass
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: